### PR TITLE
Adding ability for Snackbar's to have margins, custom backgrounds, and be positioned at the top of the container.

### PR DESCRIPTION
**Pull request by iainconnor**
Thanks for the excellent work on this library. Just a few features that were useful for us and will hopefully help others;

* Added the ability for the Snackbar to be attached to the top of the container (default is still for it to be attached to the bottom). screenshot
* Added the ability for the Snackbar to have margins (particularly useful for making sure it doesn't appear overtop of a <ToolBar>, for example. screenshot
* Added the ability for the Snackbar to have custom background. screenshot
* And, of course, all of these features work in combination with one another. screenshot screenshot

Thanks @HugoMatilla for doing a lot of this leg work, I'm just stealing the credit by wrapping it up in a merge request.

### CODE REVIEW

**Comment by HugoMatilla** [comment]
+1

**Comment by sethgho** [comment]
:+1:  this would solve exactly the problem I'm running into right now.

**Comment by wmora** [comment]
sorry guys, haven't been able to review this. Will do it this week

**Comment by wmora** [comment]
this is really good. Thanks guys!

**Pull request merged**
